### PR TITLE
Track PRs for xenserver/xenopsd, xapi-project/xenopsd and xs-opam

### PR DESCRIPTION
**Pull request by Frezzle**
Signed-off-by: Frederico Mazzone <frederico.mazzone@citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
Can you also add xs-opam?

**Comment by kc284** [comment]
Also, if the rest of the team is ok with it, I would like to remove xen-api-sdk from the blacklisted repos as some of the PRs are pure ocaml and can be reviewed from ring3 too.

**Comment by mseri** [comment]
Fine with me

**Comment by Frezzle** [comment]
@mseri Added xs-opam. @kc284, would it be better to discuss with everyone else first on Tuesday standup and have a separate PR?

**Comment by mseri** [comment]
I meant to approve, and I clicked on merge. Sorry

**Pull request merged**
